# Generated by Django 4.1.1 on 2022-10-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subscribers',
            field=models.ManyToManyField(to='bbw.siteuser'),
        ),
        migrations.AddField(
            model_name='tags',
            name='subscribers',
            field=models.ManyToManyField(to='bbw.siteuser'),
        ),
    ]
