# Generated by Django 4.1.1 on 2022-09-19 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='muted_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
