# Generated by Django 4.1.1 on 2022-09-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbw', '0002_alter_siteuser_banned_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
