# Generated by Django 4.1.1 on 2022-09-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbw', '0003_post_publication_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(through='bbw.PostsTags', to='bbw.tags'),
        ),
    ]
